package com.mitocode.model;
// default package
// Generated 24/01/2014 09:58:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * Empleado generated by hbm2java
 */


@Entity
@Table(name="empleado")  //mudança para conectar com a tabela correta
public class Empleado implements java.io.Serializable {

        @Id
        @GeneratedValue
	private int codEmpleado;
	private String nombres;
	private String apellidos;
	private char sexo;

	public Empleado() {
	}

	public Empleado(String nombres, String apellidos, char sexo) {
		this.nombres = nombres;
		this.apellidos = apellidos;
		this.sexo = sexo;
	}

	public int getCodEmpleado() {
		return this.codEmpleado;
	}

	public void setCodEmpleado(byte codEmpleado) {
		this.codEmpleado = codEmpleado;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public char getSexo() {
		return this.sexo;
	}

	public void setSexo(char sexo) {
		this.sexo = sexo;
	}

}
